version: '3.8'

services:
  app:
    build: .
    container_name: go_ffmpeg_app
    ports:
      - "8089:8089"
    volumes:
      - ./config.yaml:/app/config.yaml
    networks:
      - compose_lms_network
    restart: always

networks:
  compose_lms_network:
    external: true
